from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
import os
import cv2
import numpy as np
import base64
import sys

from fpdf import FPDF
import datetime

# Ensure the root folder is added to sys.path
ROOT = os.path.dirname(os.path.abspath(__file__))
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

# Suppress TensorFlow logging before importing TF
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

from src.predict import load_model, predict_image, make_gradcam_heatmap, preprocess_image
from src.config import IMG_SIZE

app = FastAPI(title="NeuroScan AI API")

# Allow frontend to communicate with backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Load model globally
model = load_model()

def generate_pdf_report(result, tumor_info, image_path):
    pdf = FPDF()
    pdf.add_page()
    
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 15, "NeuroScan AI: Clinical Diagnostic Report", ln=True, align="C")
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 10, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="R")
    pdf.line(10, 35, 200, 35)
    
    pdf.set_y(45)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Summary of Findings:", ln=True)
    
    pdf.set_font("Helvetica", "B", 12)
    if result.get('is_tumor', False):
        pdf.set_text_color(220, 38, 38)
        pdf.cell(0, 10, f"Pathology Detected: {result.get('label', 'Unknown').capitalize()}", ln=True)
    else:
        pdf.set_text_color(22, 163, 74)
        pdf.cell(0, 10, "No Abnormalities Detected", ln=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=11)
    pdf.cell(0, 10, f"System Confidence Score: {result.get('confidence', 0)}%", ln=True)
    
    if result.get('is_tumor', False) and tumor_info:
        pdf.set_y(85)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 10, "Anatomical Analysis", ln=True)
        pdf.line(10, 94, 60, 94)
        
        pdf.set_y(100)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(40, 10, "Anatomical Origin: ")
        pdf.set_font("Helvetica", size=11)
        pdf.cell(0, 10, f"{tumor_info.get('region', 'N/A')}", ln=True)
        
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(40, 10, "Primary Brain Part: ")
        pdf.set_font("Helvetica", size=11)
        pdf.cell(0, 10, f"{tumor_info.get('part', 'N/A')}", ln=True)
        
        pdf.set_y(130)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 10, "Diagnostic Summary:", ln=True)
        pdf.set_font("Helvetica", style="I", size=10)
        pdf.multi_cell(0, 8, f"{tumor_info.get('desc', 'N/A')}")
        
    if os.path.exists(image_path):
        try:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 10, "Analyzed MRI Scan:", ln=True)
            pdf.image(image_path, x=40, y=30, w=130)
        except Exception:
            pass

    pdf.set_y(260)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Disclaimer: This report is generated by an AI system for research purposes only.", align="C")
    
    return bytes(pdf.output())


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    temp_path = f"temp_{file.filename}"
    try:
        # Save temp file
        with open(temp_path, "wb") as f:
            f.write(await file.read())
            
        # Predict
        result = predict_image(temp_path, model)
        
        is_tumor = result["is_tumor"]
        label = result["label"].capitalize()
        
        # Clinical Insights
        insights = {
            "Glioma": {
                "region": "Intra-axial (Within brain tissue/parenchyma)",
                "part": "Cerebrum (Frontal/Temporal lobes) or Cerebellum",
                "desc": "Forms from glial supportive cells. Because they are intra-axial, they grow directly inside the functional brain tissue."
            },
            "Meningioma": {
                "region": "Extra-axial (Arachnoid layer of meninges)",
                "part": "Convexity (Brain surface) or Parasagittal/Falx",
                "desc": "Forms from arachnoid cap cells in the meninges. It grows outside the brain but creates pressure on the cerebral cortex."
            },
            "Pituitary": {
                "region": "Sella Turcica (Bony depression in sphenoid bone)",
                "part": "Pituitary Gland (Base of the brain)",
                "desc": "Forms in the master gland within the sella turcica. Located exactly behind the bridge of the nose, below the optic chiasm."
            }
        }
        
        tumor_info = insights.get(label, {"region": "Unknown", "part": "Generalized Brain Tissue", "desc": "Unknown pathology type."}) if is_tumor else None
        
        # Heatmap Generation
        img_array = preprocess_image(temp_path)
        heatmap = make_gradcam_heatmap(img_array, model)
        
        heatmap_base64 = None
        if heatmap is not None:
            original_img = cv2.imread(temp_path)
            original_img = cv2.cvtColor(original_img, cv2.COLOR_BGR2RGB)
            original_img = cv2.resize(original_img, (IMG_SIZE[1], IMG_SIZE[0]))
            
            heatmap_resized = cv2.resize(heatmap, (original_img.shape[1], original_img.shape[0]))
            heatmap_resized = np.uint8(255 * heatmap_resized)
            heatmap_colored = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)
            heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
            
            superimposed_img = cv2.addWeighted(original_img, 0.6, heatmap_colored, 0.4, 0)
            
            is_success, buffer = cv2.imencode(".jpg", cv2.cvtColor(superimposed_img, cv2.COLOR_RGB2BGR))
            if is_success:
                heatmap_base64 = base64.b64encode(buffer).decode('utf-8')
                
        # Generate PDF Report
        report_data = generate_pdf_report(result, tumor_info, temp_path)
        report_base64 = base64.b64encode(report_data).decode('utf-8')
                
        return {
            "is_tumor": is_tumor,
            "label": label,
            "probability": result["probability"],
            "confidence": result["confidence"],
            "tumor_info": tumor_info,
            "heatmap_base64": heatmap_base64,
            "report_base64": report_base64
        }
        
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

from fastapi.staticfiles import StaticFiles
app.mount("/", StaticFiles(directory="frontend", html=True), name="static")

if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
